apiVersion: v1
kind: Service
metadata:
  name: redirect
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: redirect
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: redirect
    component: redirect
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
