environment = "devel"
dns = "devel.jupyter.informaticslab.co.uk"
worker-name = "dev-jupyter-worker"
hub-name = "dev-jupyter-hub"
office-hours = "true"
host_env_file = "devel.env"
jade-secrets-file = "devel-jade-secrets"
