environment = "devel"
dns = "devel.jupyter.informaticslab.co.uk"
worker-name = "dev-jupyter-worker"
master-name = "dev-jupyter-master"
host_env_file = "devel.env"
jade-secrets-file = "devel-jade-secrets"
